In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import datetime
from datetime import datetime

# 데이터 추가

In [4]:
apart_deal = pd.read_excel('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/data/12.01_21.11 평균매매가격_아파트.xlsx')

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
apart_charter = pd.read_excel('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/data/12.01_21.11 평균전세가격_아파트.xlsx')

In [6]:
apart_rent = pd.read_excel('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/data/12.01_21.11 평균월세가격_아파트.xlsx')

## 데이터 확인

In [7]:
apart_deal.head(1)

  지 역  2012년 01월  2012년 02월  ...  2021년 09월  2021년 10월  2021년 11월
0  전국     264474     264035  ...     504121     509748     513344

[1 rows x 120 columns]

In [8]:
apart_charter.head(1)

  지 역  2012년 01월  2012년 02월  ...  2021년 09월  2021년 10월  2021년 11월
0  전국     150775     150869  ...     314123     316827     318662

[1 rows x 120 columns]

In [9]:
apart_rent.head(1)

  지 역  2015년 07월  2015년 08월  ...  2021년 09월  2021년 10월  2021년 11월
0  전국        631        631  ...        798        802        806

[1 rows x 78 columns]

## 이름 및 날짜 변경
- 1900-00-00 type
- 서울 → 서울특별시

In [10]:
apart_deal.rename(columns={'지 역':'구분'}, inplace=True)

In [11]:
apart_charter.rename(columns={'지 역':'구분'}, inplace=True)

In [12]:
apart_rent.rename(columns={'지 역':'구분'}, inplace=True)

In [13]:
apart_deal.head(2)

    구분  2012년 01월  2012년 02월  ...  2021년 09월  2021년 10월  2021년 11월
0   전국     264474     264035  ...     504121     509748     513344
1  수도권     365249     364275  ...     741851     750761     756331

[2 rows x 120 columns]

In [14]:
apart_deal.loc[apart_deal['구분'] == '서울', '구분'] = '서울특별시'

In [15]:
apart_charter.loc[apart_charter['구분'] == '서울', '구분'] = '서울특별시'

In [16]:
apart_rent.loc[apart_rent['구분'] == '서울', '구분'] = '서울특별시'

In [17]:
apart_deal.head()

      구분  2012년 01월  2012년 02월  ...  2021년 09월  2021년 10월  2021년 11월
0     전국     264474     264035  ...     504121     509748     513344
1    수도권     365249     364275  ...     741851     750761     756331
2    지방권     163394     163491  ...     289254     291913     293724
3  서울특별시     540954     538876  ...    1130427    1140659    1148288
4   강북지역     405962     405406  ...     947553     954872     960377

[5 rows x 120 columns]

In [18]:
names = []
for name in apart_deal.columns[1:]:
  name = pd.to_datetime(name, format='%Y년 %m월')
  names.append(name.strftime('%Y'))
print(names)

['2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021']

In [19]:
names.insert(0, '구분')

In [20]:
apart_deal.columns = names
apart_deal.head(2)

    구분    2012    2012    2012    2012  ...    2021    2021    2021    2021    2021
0   전국  264474  264035  263470  262630  ...  491728  498221  504121  509748  513344
1  수도권  365249  364275  362790  360918  ...  721261  731999  741851  750761  756331

[2 rows x 120 columns]

In [21]:
apart_charter.columns = names
apart_charter.head(2)

    구분    2012    2012    2012    2012  ...    2021    2021    2021    2021    2021
0   전국  150775  150869  150866  150714  ...  308699  311556  314123  316827  318662
1  수도권  190242  190339  190009  189397  ...  434833  439338  443397  447376  449902

[2 rows x 120 columns]

In [22]:
apart_rent.head(2)

    구분  2015년 07월  2015년 08월  ...  2021년 09월  2021년 10월  2021년 11월
0   전국        631        631  ...        798        802        806
1  수도권        760        759  ...       1026       1031       1037

[2 rows x 78 columns]

In [23]:
names_1 = []
for name in apart_rent.columns[1:]:
  name = pd.to_datetime(name, format='%Y년 %m월')
  names_1.append(name.strftime('%Y'))
print(names_1)

['2015', '2015', '2015', '2015', '2015', '2015', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021']

In [24]:
names_1.insert(0, '구분')

In [25]:
apart_rent.columns = names_1
apart_rent.head(2)

    구분  2015  2015  2015  2015  2015  ...  2021  2021  2021  2021  2021  2021
0   전국   631   631   631   631   631  ...   727   789   794   798   802   806
1  수도권   760   759   759   759   759  ...   924  1013  1019  1026  1031  1037

[2 rows x 78 columns]

In [26]:
apart_rent.head()

      구분  2015  2015  2015  2015  2015  ...  2021  2021  2021  2021  2021  2021
0     전국   631   631   631   631   631  ...   727   789   794   798   802   806
1    수도권   760   759   759   759   759  ...   924  1013  1019  1026  1031  1037
2    지방권   508   508   508   508   508  ...   543   587   590   592   594   597
3  서울특별시   909   907   908   907   909  ...  1139  1214  1222  1228  1234  1241
4   강북지역   795   794   795   789   788  ...  1014  1152  1162  1166  1172  1178

[5 rows x 78 columns]

In [27]:
#apart_deal = apart_deal.groupby(apart_deal['구분']).mean()
#apart_charter = apart_charter.groupby(apart_charter['구분']).mean()
#apart_rent = apart_rent.groupby(apart_rent['구분']).mean()

# 세부 데이터 편집
- 1. 열-행 바꾸기
- 2. 컬럼삽입 : 구분 / 매매-전세-월세
- 3. 병합하기 : 날짜/구분 기준

## 매매

In [28]:
apart_deal = apart_deal.transpose()
apart_deal.head(2)

          0       1       2       3   ...      32       33      34      35
구분        전국     수도권     지방권   서울특별시  ...     서초구      강남구     송파구     강동구
2012  264474  365249  163394  540954  ...  972183  1050728  773923  503029

[2 rows x 36 columns]

In [29]:
apart_deal.rename(columns=apart_deal.iloc[0], inplace=True)
apart_deal = apart_deal.drop(apart_deal.index[0])
apart_deal = apart_deal.reset_index()
apart_deal.head(2)

  index      전국     수도권     지방권  ...     서초구      강남구     송파구     강동구
0  2012  264474  365249  163394  ...  972183  1050728  773923  503029
1  2012  264035  364275  163491  ...  961583  1047151  764754  502039

[2 rows x 37 columns]

In [30]:
apart_deal.rename(columns = {'index':'날짜'}, inplace=True)

In [31]:
apart_deal.insert(1, '구분', '매매')
apart_deal.head(2)

     날짜  구분      전국     수도권     지방권  ...     동남권     서초구      강남구     송파구     강동구
0  2012  매매  264474  365249  163394  ...  850021  972183  1050728  773923  503029
1  2012  매매  264035  364275  163491  ...  843792  961583  1047151  764754  502039

[2 rows x 38 columns]

In [32]:
apart_deal = apart_deal[['날짜', '구분', '전국','수도권',	'지방권', '서울특별시',	'도심권',	'종로구',	'중구',	'용산구', '강북지역',	'동북권',	'성동구',	'광진구',	'동대문구',	'중랑구',	'성북구',	'강북구',	'도봉구',	'노원구',	'서북권', '은평구',	'서대문구',	'마포구'	,'강남지역','동남권',	'서초구',	'강남구',	'송파구',	'강동구',	'서남권',	'양천구',	'강서구'	,'구로구'	,'금천구',	'영등포구',	'동작구',	'관악구']]
apart_deal

       날짜  구분      전국     수도권     지방권  ...     구로구     금천구     영등포구      동작구     관악구
0    2012  매매  264474  365249  163394  ...  351344  282328   541840   494561  393049
1    2012  매매  264035  364275  163491  ...  350573  283190   541255   493439  392874
2    2012  매매  263470  362790  163849  ...  350500  282241   537500   492037  387448
3    2012  매매  262630  360918  164044  ...  350000  281897   535787   486354  385136
4    2012  매매  261823  359253  164096  ...  348365  280690   534660   484256  382249
..    ...  ..     ...     ...     ...  ...     ...     ...      ...      ...     ...
114  2021  매매  491728  721261  284270  ...  665836  638543  1139713  1065149  745299
115  2021  매매  498221  731999  286926  ...  671066  641853  1147357  1074886  753247
116  2021  매매  504121  741851  289254  ...  677414  646434  1156448  1085873  759655
117  2021  매매  509748  750761  291913  ...  683172  651938  1163800  1095958  765529
118  2021  매매  513344  756331  293724  ...  688553  654875  1168135  1103453  766920

[119 rows x 38 columns]

## 전세

In [33]:
apart_charter = apart_charter.transpose()
apart_charter.rename(columns=apart_charter.iloc[0], inplace=True)
apart_charter = apart_charter.drop(apart_charter.index[0])
apart_charter = apart_charter.reset_index()
apart_charter.rename(columns = {'index':'날짜'}, inplace=True) 
apart_charter.insert(1, '구분', '전세')
apart_charter = apart_charter[['날짜', '구분', '전국','수도권',	'지방권', '서울특별시',	'도심권',	'종로구',	'중구',	'용산구', '강북지역',	'동북권',	'성동구',	'광진구',	'동대문구',	'중랑구',	'성북구',	'강북구',	'도봉구',	'노원구',	'서북권', '은평구',	'서대문구',	'마포구'	,'강남지역','동남권',	'서초구',	'강남구',	'송파구',	'강동구',	'서남권',	'양천구',	'강서구'	,'구로구'	,'금천구',	'영등포구',	'동작구',	'관악구']]
apart_charter

       날짜  구분      전국     수도권     지방권  ...     구로구     금천구    영등포구     동작구     관악구
0    2012  전세  150775  190242  111187  ...  201906  160086  268415  284378  228325
1    2012  전세  150869  190339  111279  ...  201510  162931  267926  286244  229125
2    2012  전세  150866  190009  111604  ...  201667  162241  268160  285902  229688
3    2012  전세  150714  189397  111914  ...  201042  161638  268617  286634  229863
4    2012  전세  150544  188824  112148  ...  199531  162328  268585  285171  228950
..    ...  ..     ...     ...     ...  ...     ...     ...     ...     ...     ...
114  2021  전세  308699  434833  194696  ...  421051  380578  581962  640281  472391
115  2021  전세  311556  439338  196062  ...  423385  382647  585631  646234  475782
116  2021  전세  314123  443397  197281  ...  426186  385275  589997  651562  478828
117  2021  전세  316827  447376  198833  ...  428658  388477  594935  656388  480299
118  2021  전세  318662  449902  200045  ...  431477  388934  598348  659353  480741

[119 rows x 38 columns]

## 월세

In [34]:
apart_rent = apart_rent.transpose()
apart_rent.rename(columns=apart_rent.iloc[0], inplace=True)
apart_rent = apart_rent.drop(apart_rent.index[0])
apart_rent = apart_rent.reset_index()
apart_rent.rename(columns = {'index':'날짜'}, inplace=True) 
apart_rent.insert(1, '구분', '월세')
apart_rent = apart_rent[['날짜', '구분', '전국','수도권',	'지방권', '서울특별시',	'도심권',	'종로구',	'중구',	'용산구', '강북지역',	'동북권',	'성동구',	'광진구',	'동대문구',	'중랑구',	'성북구',	'강북구',	'도봉구',	'노원구',	'서북권', '은평구',	'서대문구',	'마포구'	,'강남지역','동남권',	'서초구',	'강남구',	'송파구',	'강동구',	'서남권',	'양천구',	'강서구'	,'구로구'	,'금천구',	'영등포구',	'동작구',	'관악구']]
apart_rent

      날짜  구분   전국   수도권  지방권 서울특별시   도심권  ...  양천구  강서구  구로구  금천구 영등포구   동작구  관악구
0   2015  월세  631   760  508   909  1116  ...  860  745  762  712  917   663  712
1   2015  월세  631   759  508   907  1116  ...  860  745  738  668  922   663  713
2   2015  월세  631   759  508   908  1118  ...  860  746  725  669  926   663  709
3   2015  월세  631   759  508   907  1119  ...  861  751  724  666  927   664  718
4   2015  월세  631   759  508   909  1120  ...  860  755  725  666  906   666  720
..   ...  ..  ...   ...  ...   ...   ...  ...  ...  ...  ...  ...  ...   ...  ...
72  2021  월세  789  1013  587  1214  1626  ...  932  868  795  939  957  1098  808
73  2021  월세  794  1019  590  1222  1632  ...  931  878  795  939  958  1115  810
74  2021  월세  798  1026  592  1228  1639  ...  932  872  798  940  959  1131  812
75  2021  월세  802  1031  594  1234  1643  ...  933  876  798  941  963  1142  813
76  2021  월세  806  1037  597  1241  1653  ...  933  882  798  941  963  1149  813

[77 rows x 38 columns]

# 합본

## 전체

In [35]:
Total = pd.merge(left=apart_deal, right=apart_charter, on= ['날짜', '구분', '전국','수도권',	'지방권', '서울특별시',	'도심권',	'종로구',	'중구',	'용산구', '강북지역',	'동북권',	'성동구',	'광진구',	'동대문구',	'중랑구',	'성북구',	'강북구',	'도봉구',	'노원구',	'서북권', '은평구',	'서대문구',	'마포구'	,'강남지역','동남권',	'서초구',	'강남구',	'송파구',	'강동구',	'서남권',	'양천구',	'강서구'	,'구로구'	,'금천구',	'영등포구',	'동작구',	'관악구'], how='outer')
Total = Total.sort_values(by='날짜')
Total = Total.reset_index()
Total.drop(columns='index', inplace=True)
Total = pd.merge(left=Total, right=apart_rent, on= ['날짜', '구분', '전국','수도권',	'지방권', '서울특별시',	'도심권',	'종로구',	'중구',	'용산구', '강북지역',	'동북권',	'성동구',	'광진구',	'동대문구',	'중랑구',	'성북구',	'강북구',	'도봉구',	'노원구',	'서북권', '은평구',	'서대문구',	'마포구'	,'강남지역','동남권',	'서초구',	'강남구',	'송파구',	'강동구',	'서남권',	'양천구',	'강서구'	,'구로구'	,'금천구',	'영등포구',	'동작구',	'관악구'], how='outer')
Total = Total.sort_values(by='날짜')
Total = Total.reset_index()
Total.drop(columns='index', inplace=True)
Total

       날짜  구분        전국       수도권  ...       금천구       영등포구        동작구       관악구
0    2012  매매  264474.0  365249.0  ...  282328.0   541840.0   494561.0  393049.0
1    2012  매매  251459.0  339555.0  ...  274190.0   498128.0   451305.0  366925.0
2    2012  매매  253440.0  343658.0  ...  274414.0   501628.0   454927.0  369138.0
3    2012  매매  254426.0  345665.0  ...  274362.0   507904.0   458927.0  372936.0
4    2012  매매  255680.0  348174.0  ...  274172.0   512574.0   464451.0  375025.0
..    ...  ..       ...       ...  ...       ...        ...        ...       ...
310  2021  매매  509748.0  750761.0  ...  651938.0  1163800.0  1095958.0  765529.0
311  2021  매매  498221.0  731999.0  ...  641853.0  1147357.0  1074886.0  753247.0
312  2021  매매  491728.0  721261.0  ...  638543.0  1139713.0  1065149.0  745299.0
313  2021  전세  256587.0  346541.0  ...  330308.0   433771.0   514548.0  362837.0
314  2021  월세     806.0    1037.0  ...     941.0      963.0     1149.0     813.0

[315 rows x 38 columns]

In [36]:
Total.to_csv('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/전처리/아파트 평균 가격 총합(종합)2.csv')

## 대분류
- [구] 삭제

In [37]:
Total_A = Total

In [38]:
Total_A.drop(columns=['종로구',	'중구',	'용산구','성동구',	'광진구',	'동대문구',	'중랑구',	'성북구',	'강북구',	'도봉구',	'노원구', '은평구',	'서대문구',	'마포구',	'서초구',	'강남구',	'송파구',	'강동구','양천구',	'강서구'	,'구로구'	,'금천구',	'영등포구',	'동작구',	'관악구'], inplace=True)

In [39]:
Total_A

       날짜  구분        전국       수도권  ...       서북권       강남지역        동남권       서남권
0    2012  매매  264474.0  365249.0  ...  428866.0   649861.0   850021.0  452515.0
1    2012  매매  251459.0  339555.0  ...  413802.0   593957.0   769532.0  419715.0
2    2012  매매  253440.0  343658.0  ...  418173.0   599794.0   778766.0  423340.0
3    2012  매매  254426.0  345665.0  ...  418245.0   602648.0   781434.0  426376.0
4    2012  매매  255680.0  348174.0  ...  419474.0   607292.0   787984.0  429140.0
..    ...  ..       ...       ...  ...       ...        ...        ...       ...
310  2021  매매  509748.0  750761.0  ...  981723.0  1319575.0  1810205.0  942268.0
311  2021  매매  498221.0  731999.0  ...  963766.0  1291275.0  1764430.0  927408.0
312  2021  매매  491728.0  721261.0  ...  956231.0  1279123.0  1745838.0  920207.0
313  2021  전세  256587.0  346541.0  ...  457322.0   562243.0   727843.0  412657.0
314  2021  월세     806.0    1037.0  ...    1174.0     1301.0     1793.0     922.0

[315 rows x 13 columns]

In [40]:
Total_A.to_csv('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/전처리/아파트 평균 가격 총합(전국,수도,지방 포함)2.csv')

## 서울특별시 외 제외

In [41]:
Total_B = Total_A

In [42]:
Total_B.drop(columns=['전국','수도권','지방권'], inplace=True)

In [43]:
Total_B.head(2)

     날짜  구분     서울특별시       도심권  ...       서북권      강남지역       동남권       서남권
0  2012  매매  540954.0  706316.0  ...  428866.0  649861.0  850021.0  452515.0
1  2012  매매  499900.0  664990.0  ...  413802.0  593957.0  769532.0  419715.0

[2 rows x 10 columns]

In [44]:
Total_B.to_csv('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/전처리/아파트 평균 가격 총합(서울권)2.csv')

# 규모별 아파트 가격

### 매매

In [45]:
apart_deal_1 = pd.read_excel('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/data/12.01_21.11 규모별_아파트_매매_평균가격.xlsx')
apart_deal_1

   지역   규모  2006년 01월  2006년 02월  ...  2021년 07월  2021년 08월  2021년 09월  2021년 10월
0  전국  초소형      246.2      195.4  ...      449.6      409.1      417.3      380.3
1  전국   소형      235.8      196.6  ...      500.7      488.7      456.4      413.4
2  전국  중소형      298.1      257.9  ...      547.9      551.4      535.3      488.1
3  전국  중대형      415.2      356.8  ...      632.8      617.0      613.4      570.9
4  전국   대형      519.1      455.3  ...      658.4      627.7      642.9      633.7
5  서울  초소형      482.8      398.1  ...     1407.1     1268.1     1365.3     1232.4
6  서울   소형      463.8      396.3  ...     1464.4     1505.3     1554.9     1589.9
7  서울  중소형      500.7      466.1  ...     1339.9     1411.3     1483.7     1432.4
8  서울  중대형      630.0      572.5  ...     1363.8     1368.6     1457.6     1449.9
9  서울   대형      771.7      753.9  ...     1672.1     1604.3     1595.2     1780.2

[10 rows x 192 columns]

In [46]:
names_4 = []
for name in apart_deal_1.columns[2:]:
  name = pd.to_datetime(name, format='%Y년 %m월')
  names_4.append(name.strftime('%Y'))
print(names_4)

['2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021']

In [47]:
names_4.insert(0, '구분')

In [48]:
names_4.insert(0, '지역')

In [49]:
apart_deal_1.columns = names_4
apart_deal_1.head(2)

   지역   구분   2006   2006   2006  ...   2021   2021   2021   2021   2021
0  전국  초소형  246.2  195.4  230.1  ...  413.9  449.6  409.1  417.3  380.3
1  전국   소형  235.8  196.6  215.3  ...  456.3  500.7  488.7  456.4  413.4

[2 rows x 192 columns]

####크기구분

#### 소형

In [50]:
SSize_1 = apart_deal_1['구분'] == '초소형'
SSize_1 = apart_deal_1[SSize_1]

In [51]:
SSize_1

   지역   구분   2006   2006   2006  ...    2021    2021    2021    2021    2021
0  전국  초소형  246.2  195.4  230.1  ...   413.9   449.6   409.1   417.3   380.3
5  서울  초소형  482.8  398.1  501.2  ...  1284.5  1407.1  1268.1  1365.3  1232.4

[2 rows x 192 columns]

In [52]:
SSize_2 = apart_deal_1['구분'] == '소형'
SSize_2 = apart_deal_1[SSize_2]

In [53]:
SSize_2

   지역  구분   2006   2006   2006  ...    2021    2021    2021    2021    2021
1  전국  소형  235.8  196.6  215.3  ...   456.3   500.7   488.7   456.4   413.4
6  서울  소형  463.8  396.3  452.4  ...  1411.1  1464.4  1505.3  1554.9  1589.9

[2 rows x 192 columns]

In [54]:
SSize = pd.concat([SSize_1, SSize_2])
SSize

   지역   구분   2006   2006   2006  ...    2021    2021    2021    2021    2021
0  전국  초소형  246.2  195.4  230.1  ...   413.9   449.6   409.1   417.3   380.3
5  서울  초소형  482.8  398.1  501.2  ...  1284.5  1407.1  1268.1  1365.3  1232.4
1  전국   소형  235.8  196.6  215.3  ...   456.3   500.7   488.7   456.4   413.4
6  서울   소형  463.8  396.3  452.4  ...  1411.1  1464.4  1505.3  1554.9  1589.9

[4 rows x 192 columns]

In [55]:
SSize.drop(columns='구분', inplace=True)

In [56]:
SSize = SSize.groupby(SSize['지역']).mean()

In [57]:
SSize

     2006   2006   2006   2006  ...     2021    2021     2021     2021
지역                              ...
서울  473.3  397.2  476.8  423.1  ...  1435.75  1386.7  1460.10  1411.15
전국  241.0  196.0  222.7  217.0  ...   475.15   448.9   436.85   396.85

[2 rows x 190 columns]

In [58]:
SSize = SSize.reset_index()
SSize = SSize.transpose()
SSize.rename(columns=SSize.iloc[0], inplace=True)
SSize = SSize.drop(SSize.index[0])
SSize = SSize.reset_index()
SSize.rename(columns = {'index':'날짜'}, inplace=True) 
SSize.insert(1, '구분', '소형')
SSize

       날짜  구분       서울      전국
0    2006  소형    473.3     241
1    2006  소형    397.2     196
2    2006  소형    476.8   222.7
3    2006  소형    423.1     217
4    2006  소형   402.55  206.85
..    ...  ..      ...     ...
185  2021  소형   1347.8   435.1
186  2021  소형  1435.75  475.15
187  2021  소형   1386.7   448.9
188  2021  소형   1460.1  436.85
189  2021  소형  1411.15  396.85

[190 rows x 4 columns]

#### 중형

In [59]:
MSize_1 = apart_deal_1['구분'] == '중소형'
MSize_1 = apart_deal_1[MSize_1]

In [60]:
MSize_2 = apart_deal_1['구분'] == '중대형'
MSize_2 = apart_deal_1[MSize_2]

In [61]:
MSize = pd.concat([MSize_1, MSize_2])
MSize.drop(columns='구분', inplace=True)
MSize = MSize.groupby(MSize['지역']).mean()
MSize = MSize.reset_index()
MSize = MSize.transpose()
MSize.rename(columns=MSize.iloc[0], inplace=True)
MSize = MSize.drop(MSize.index[0])
MSize = MSize.reset_index()
MSize.rename(columns = {'index':'날짜'}, inplace=True) 
MSize.insert(1, '구분', '중형')
MSize

       날짜  구분       서울      전국
0    2006  중형   565.35  356.65
1    2006  중형    519.3  307.35
2    2006  중형   533.65   328.7
3    2006  중형    482.3  299.65
4    2006  중형    443.4  283.95
..    ...  ..      ...     ...
185  2021  중형  1347.85   541.1
186  2021  중형  1351.85  590.35
187  2021  중형  1389.95   584.2
188  2021  중형  1470.65  574.35
189  2021  중형  1441.15   529.5

[190 rows x 4 columns]

#### 대형

In [62]:
LSize = apart_deal_1['구분'] == '대형'
LSize = apart_deal_1[LSize]

In [63]:
LSize

   지역  구분   2006   2006   2006  ...    2021    2021    2021    2021    2021
4  전국  대형  519.1  455.3  474.5  ...   576.9   658.4   627.7   642.9   633.7
9  서울  대형  771.7  753.9  802.3  ...  1407.5  1672.1  1604.3  1595.2  1780.2

[2 rows x 192 columns]

In [64]:
LSize.drop(columns='구분', inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [65]:
LSize

   지역   2006   2006   2006   2006  ...    2021    2021    2021    2021    2021
4  전국  519.1  455.3  474.5  401.2  ...   576.9   658.4   627.7   642.9   633.7
9  서울  771.7  753.9  802.3  713.9  ...  1407.5  1672.1  1604.3  1595.2  1780.2

[2 rows x 191 columns]

In [66]:
LSize = LSize.transpose()
LSize.rename(columns=LSize.iloc[0], inplace=True)
LSize = LSize.drop(LSize.index[0])
LSize = LSize.reset_index()
LSize

    index     전국      서울
0    2006  519.1   771.7
1    2006  455.3   753.9
2    2006  474.5   802.3
3    2006  401.2   713.9
4    2006  337.9   638.2
..    ...    ...     ...
185  2021  576.9  1407.5
186  2021  658.4  1672.1
187  2021  627.7  1604.3
188  2021  642.9  1595.2
189  2021  633.7  1780.2

[190 rows x 3 columns]

In [67]:
LSize.rename(columns = {'index':'날짜'}, inplace=True) 
LSize.insert(1, '구분', '대형')
LSize

       날짜  구분     전국      서울
0    2006  대형  519.1   771.7
1    2006  대형  455.3   753.9
2    2006  대형  474.5   802.3
3    2006  대형  401.2   713.9
4    2006  대형  337.9   638.2
..    ...  ..    ...     ...
185  2021  대형  576.9  1407.5
186  2021  대형  658.4  1672.1
187  2021  대형  627.7  1604.3
188  2021  대형  642.9  1595.2
189  2021  대형  633.7  1780.2

[190 rows x 4 columns]

#### 합본

In [68]:
deal = pd.merge(left=SSize, right=MSize, on= ['날짜', '구분', '전국', '서울'], how='outer')
deal = deal.sort_values(by='날짜')
deal = deal.reset_index()
deal.drop(columns='index', inplace=True)
deal

       날짜  구분       서울      전국
0    2006  소형   473.30  241.00
1    2006  중형   437.70  264.35
2    2006  중형   403.35  249.10
3    2006  중형   417.45  254.45
4    2006  중형   443.40  283.95
..    ...  ..      ...     ...
375  2021  소형  1264.15  398.20
376  2021  소형  1281.35  418.75
377  2021  소형  1317.50  449.30
378  2021  중형  1470.65  574.35
379  2021  중형  1441.15  529.50

[380 rows x 4 columns]

In [69]:
deal = pd.merge(left=deal, right=LSize, on= ['날짜', '구분', '전국', '서울'], how='outer')
deal = deal.sort_values(by='날짜')
deal = deal.reset_index()
deal.drop(columns='index', inplace=True)
deal

       날짜  구분       서울      전국
0    2006  소형   473.30  241.00
1    2006  소형   397.40  239.90
2    2006  소형   476.80  222.70
3    2006  소형   397.20  196.00
4    2006  대형   771.70  519.10
..    ...  ..      ...     ...
565  2021  중형  1347.85  541.10
566  2021  중형  1351.85  590.35
567  2021  중형  1389.95  584.20
568  2021  소형  1411.15  396.85
569  2021  대형  1780.20  633.70

[570 rows x 4 columns]

In [70]:
deal.rename(columns={'구분':'크기'}, inplace=True)

In [71]:
deal.insert(1, '구분', '매매')

In [72]:
deal

       날짜  구분  크기       서울      전국
0    2006  매매  소형   473.30  241.00
1    2006  매매  소형   397.40  239.90
2    2006  매매  소형   476.80  222.70
3    2006  매매  소형   397.20  196.00
4    2006  매매  대형   771.70  519.10
..    ...  ..  ..      ...     ...
565  2021  매매  중형  1347.85  541.10
566  2021  매매  중형  1351.85  590.35
567  2021  매매  중형  1389.95  584.20
568  2021  매매  소형  1411.15  396.85
569  2021  매매  대형  1780.20  633.70

[570 rows x 5 columns]

In [73]:
deal.to_csv('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/전처리/규모별 매매 평균 가격 총합2.csv')

### 전세

In [74]:
apart_charter_1= pd.read_excel('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/data/12.01_21.11 규모별_아파트_전세_평균가격.xlsx')
apart_charter_1.head()

  지 역   규모  2014년 01월  2014년 02월  ...  2021년 06월  2021년 07월  2021년 08월  2021년 09월
0  전국  초소형      238.9      221.0  ...      506.4      506.9      477.0      477.4
1  전국   소형      252.4      251.7  ...      428.1      436.2      428.3      425.4
2  전국  중소형      270.0      267.9  ...      450.2      453.9      457.7      456.0
3  전국  중대형      310.2      295.7  ...      495.4      505.2      511.3      510.1
4  전국   대형      268.6      273.2  ...      489.5      496.0      486.3      487.9

[5 rows x 95 columns]

In [75]:
names_3 = []
for name in apart_charter_1.columns[2:]:
  name = pd.to_datetime(name, format='%Y년 %m월')
  names_3.append(name.strftime('%Y'))

In [76]:
names_3.insert(0, '구분')

In [77]:
names_3.insert(0, '지역')

In [78]:
apart_charter_1.columns = names_3
apart_charter_1.head(2)

   지역   구분   2014   2014   2014  ...   2021   2021   2021   2021   2021
0  전국  초소형  238.9  221.0  220.6  ...  509.2  506.4  506.9  477.0  477.4
1  전국   소형  252.4  251.7  246.7  ...  436.5  428.1  436.2  428.3  425.4

[2 rows x 95 columns]

#### 크기구분

#### 소형

In [79]:
SSize_1 = apart_charter_1['구분'] == '초소형'
SSize_1 = apart_charter_1[SSize_1]

In [80]:
SSize_2 = apart_charter_1['구분'] == '소형'
SSize_2 = apart_charter_1[SSize_2]

In [81]:
SSize = pd.concat([SSize_1, SSize_2])
SSize.drop(columns='구분', inplace=True)
SSize = SSize.groupby(SSize['지역']).mean()
SSize = SSize.reset_index()
SSize = SSize.transpose()
SSize.rename(columns=SSize.iloc[0], inplace=True)
SSize = SSize.drop(SSize.index[0])
SSize = SSize.reset_index()
SSize.rename(columns = {'index':'날짜'}, inplace=True) 
SSize.insert(1, '구분', '소형')
SSize

      날짜  구분      서울      전국
0   2014  소형   395.3  245.65
1   2014  소형  387.05  236.35
2   2014  소형  380.45  233.65
3   2014  소형  383.75  236.75
4   2014  소형  388.05  240.05
..   ...  ..     ...     ...
88  2021  소형  795.05  472.85
89  2021  소형  794.35  467.25
90  2021  소형  783.55  471.55
91  2021  소형  751.95  452.65
92  2021  소형  777.35   451.4

[93 rows x 4 columns]

#### 중형

In [82]:
MSize_1 = apart_charter_1['구분'] == '중소형'
MSize_1 = apart_charter_1[MSize_1]

In [83]:
MSize_2 = apart_charter_1['구분'] == '중대형'
MSize_2 = apart_charter_1[MSize_2]

In [84]:
MSize = pd.concat([MSize_1, MSize_2])
MSize.drop(columns='구분', inplace=True)
MSize = MSize.groupby(MSize['지역']).mean()
MSize = MSize.reset_index()
MSize = MSize.transpose()
MSize.rename(columns=MSize.iloc[0], inplace=True)
MSize = MSize.drop(MSize.index[0])
MSize = MSize.reset_index()
MSize.rename(columns = {'index':'날짜'}, inplace=True) 
MSize.insert(1, '구분', '중형')
MSize

      날짜  구분      서울      전국
0   2014  중형  388.65   290.1
1   2014  중형   384.4   281.8
2   2014  중형  379.75  278.75
3   2014  중형   381.2   284.5
4   2014  중형   380.7  283.35
..   ...  ..     ...     ...
88  2021  중형   745.9  513.45
89  2021  중형  727.55   472.8
90  2021  중형   726.4  479.55
91  2021  중형   723.7   484.5
92  2021  중형  731.95  483.05

[93 rows x 4 columns]

#### 대형

In [85]:
LSize = apart_charter_1['구분'] == '대형'
LSize = apart_charter_1[LSize]

In [86]:
LSize.drop(columns='구분', inplace=True)
LSize = LSize.transpose()
LSize.rename(columns=LSize.iloc[0], inplace=True)
LSize = LSize.drop(LSize.index[0])
LSize = LSize.reset_index()
LSize.rename(columns = {'index':'날짜'}, inplace=True) 
LSize.insert(1, '구분', '대형')
LSize

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

      날짜  구분     전국     서울
0   2014  대형  268.6  434.7
1   2014  대형  273.2  420.8
2   2014  대형  265.6  440.1
3   2014  대형  266.6    445
4   2014  대형  268.1  438.3
..   ...  ..    ...    ...
88  2021  대형  513.6  839.7
89  2021  대형  489.5  831.2
90  2021  대형    496  801.6
91  2021  대형  486.3  801.6
92  2021  대형  487.9  764.7

[93 rows x 4 columns]

####합본

In [87]:
charter = pd.merge(left=SSize, right=MSize, on= ['날짜', '구분', '전국', '서울'], how='outer')
charter = charter.sort_values(by='날짜')
charter = charter.reset_index()
charter.drop(columns='index', inplace=True)
charter

       날짜  구분      서울      전국
0    2014  소형  395.30  245.65
1    2014  중형  401.30  290.15
2    2014  중형  389.40  285.65
3    2014  중형  392.90  283.85
4    2014  중형  387.95  274.40
..    ...  ..     ...     ...
181  2021  소형  771.10  451.85
182  2021  소형  772.05  445.85
183  2021  소형  788.45  454.40
184  2021  중형  723.70  484.50
185  2021  중형  731.95  483.05

[186 rows x 4 columns]

In [88]:
charter = pd.merge(left=charter, right=LSize, on= ['날짜', '구분', '전국', '서울'], how='outer')
charter = charter.sort_values(by='날짜')
charter = charter.reset_index()
charter.drop(columns='index', inplace=True)
charter

       날짜  구분      서울      전국
0    2014  소형  395.30  245.65
1    2014  소형  409.00  251.75
2    2014  소형  380.45  233.65
3    2014  소형  387.05  236.35
4    2014  소형  417.10  259.60
..    ...  ..     ...     ...
274  2021  중형  745.90  513.45
275  2021  중형  727.55  472.80
276  2021  중형  726.40  479.55
277  2021  소형  777.35  451.40
278  2021  대형  764.70  487.90

[279 rows x 4 columns]

In [89]:
charter.rename(columns={'구분':'크기'}, inplace=True)
charter.insert(1, '구분', '전세')
charter

       날짜  구분  크기      서울      전국
0    2014  전세  소형  395.30  245.65
1    2014  전세  소형  409.00  251.75
2    2014  전세  소형  380.45  233.65
3    2014  전세  소형  387.05  236.35
4    2014  전세  소형  417.10  259.60
..    ...  ..  ..     ...     ...
274  2021  전세  중형  745.90  513.45
275  2021  전세  중형  727.55  472.80
276  2021  전세  중형  726.40  479.55
277  2021  전세  소형  777.35  451.40
278  2021  전세  대형  764.70  487.90

[279 rows x 5 columns]

In [90]:
charter.to_csv('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/전처리/규모별 전세 평균 가격 총합2.csv')

## 총합

In [91]:
Total = pd.merge(left=deal, right=charter, on= ['날짜', '구분', '크기',  '전국', '서울'], how='outer')
Total = Total.sort_values(by=['날짜', '구분'] ,ascending=True)
Total = Total.reset_index()
Total.drop(columns='index', inplace=True)
Total

       날짜  구분  크기      서울      전국
0    2006  매매  소형  473.30  241.00
1    2006  매매  소형  397.40  239.90
2    2006  매매  소형  476.80  222.70
3    2006  매매  소형  397.20  196.00
4    2006  매매  대형  771.70  519.10
..    ...  ..  ..     ...     ...
844  2021  전세  중형  745.90  513.45
845  2021  전세  중형  727.55  472.80
846  2021  전세  중형  726.40  479.55
847  2021  전세  소형  777.35  451.40
848  2021  전세  대형  764.70  487.90

[849 rows x 5 columns]

In [92]:
Total.to_csv('/content/drive/MyDrive/[D9&10] 데이터시각화 프로젝트_3조/김장현/전처리/규모별 평균 가격 총합(종합)2.csv')